name: Playwright Tests

on:
  push:
    branches: [ main ]   # runs on push to main branch
  pull_request:
    branches: [ main ]   # also runs on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # ✅ upgrade to Node.js 20 for Azure deps

      - name: Install dependencies
        run: npm ci --no-optional   # ✅ skip fsevents (mac-only)

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test tests/ui --reporter=html   # ✅ generate HTML report

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
